language: scala
git:
  depth: 50
scala:
- 2.10.5
- 2.11.7
script:
- if [[ "$TRAVIS_PULL_REQUEST" == "false" &&
        "$TRAVIS_BRANCH" == "dev" &&
        $(cat version.sbt) =~ "-SNAPSHOT"
  ]]; then
    sbt ++$TRAVIS_SCALA_VERSION coverage compile test coverageReport && bash <(curl -s https://codecov.io/bash) && sbt clean compile test publish gitSnapshots publish ;
  else
    sbt ++$TRAVIS_SCALA_VERSION coverage compile test coverageReport && bash <(curl -s https://codecov.io/bash) && sbt clean compile test publishLocal ;
  fi
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/NX9T51sqZ7a2U3zE8Thm
    - https://webhooks.gitter.im/e/42e709a53fb8e39472d3
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
